#!/bin/bash

# 1024/750 (128/93.75)

tc qdisc del root dev eth1 2> /dev/null
tc qdisc del root dev br0 2> /dev/null

if [ "$1" != 'start' ]; then
	exit
fi

echo htb...

#
# Wychodzacy
#

tc qdisc add dev eth1 root handle 1:0 htb
tc class add dev eth1 parent 1:0 classid 1:1 htb rate 94kbps ceil 94kbps

# q3
tc class add dev eth1 parent 1:1 classid 1:2 htb rate 50kbps ceil 90kbps prio 1
# ssh, telnet, ftp21
tc class add dev eth1 parent 1:1 classid 1:3 htb rate 20kbps ceil 20kbps prio 2
# default
tc class add dev eth1 parent 1:1 classid 1:4 htb rate 20kbps ceil 94kbps prio 3
# p2p
tc class add dev eth1 parent 1:1 classid 1:5 htb rate  4kbps ceil 70kbps prio 4

tc filter add dev eth1 protocol ip parent 1:0 handle 1 fw flowid 1:2
tc filter add dev eth1 protocol ip parent 1:0 handle 2 fw flowid 1:3
tc filter add dev eth1 protocol ip parent 1:0 handle 3 fw flowid 1:4
tc filter add dev eth1 protocol ip parent 1:0 handle 4 fw flowid 1:5

tc qdisc add dev eth1 parent 1:2 handle 2:0 sfq perturb 10
tc qdisc add dev eth1 parent 1:3 handle 3:0 sfq perturb 10
tc qdisc add dev eth1 parent 1:4 handle 4:0 sfq perturb 10
tc qdisc add dev eth1 parent 1:5 handle 5:0 sfq perturb 10

#
# Przychodzacy
#

tc qdisc add dev br0 root handle 1:0 htb
tc class add dev br0 parent 1:0 classid 1:1 htb rate 101mbit ceil 101mbit

tc class add dev br0 parent 1:1 classid 1:2 htb rate 100mbit ceil 100mbit
tc class add dev br0 parent 1:1 classid 1:3 htb rate 128kbps ceil 128kbps

# q3
tc class add dev br0 parent 1:3 classid 1:4 htb rate 71kbps ceil 100kbps prio 1
# ssh, telnet, ftp21
tc class add dev br0 parent 1:3 classid 1:5 htb rate 21kbps ceil 100kbps prio 2
# default
tc class add dev br0 parent 1:3 classid 1:6 htb rate 32kbps ceil 128kbps prio 3
# p2p
tc class add dev br0 parent 1:3 classid 1:7 htb rate  4kbps ceil 128kbps prio 4

tc filter add dev br0 protocol ip parent 1:0 handle 1 fw flowid 1:4
tc filter add dev br0 protocol ip parent 1:0 handle 2 fw flowid 1:5
tc filter add dev br0 protocol ip parent 1:0 handle 3 fw flowid 1:6
tc filter add dev br0 protocol ip parent 1:0 handle 4 fw flowid 1:7

tc qdisc add dev br0 parent 1:4 handle 2:0 sfq perturb 10
tc qdisc add dev br0 parent 1:5 handle 3:0 sfq perturb 10
tc qdisc add dev br0 parent 1:6 handle 4:0 sfq perturb 10
tc qdisc add dev br0 parent 1:7 handle 5:0 sfq perturb 10


iptables -t mangle -F POSTROUTING

# q3
iptables -t mangle -A POSTROUTING -o eth1 -p udp --dport 27963 -j MARK --set-mark 0x1
iptables -t mangle -A POSTROUTING -o eth1 -p udp --dport 27963 -j RETURN
iptables -t mangle -A POSTROUTING -o eth1 -p udp --dport 44830 -j MARK --set-mark 0x1
iptables -t mangle -A POSTROUTING -o eth1 -p udp --dport 44830 -j RETURN
iptables -t mangle -A POSTROUTING -o eth1 -p udp --sport 27963 -j MARK --set-mark 0x1
iptables -t mangle -A POSTROUTING -o eth1 -p udp --sport 27963 -j RETURN
iptables -t mangle -A POSTROUTING -o eth1 -p udp --sport 44830 -j MARK --set-mark 0x1
iptables -t mangle -A POSTROUTING -o eth1 -p udp --sport 44830 -j RETURN

#default
iptables -t mangle -A POSTROUTING -o eth1 -j MARK --set-mark 0x3
# iptables -t mangle -A POSTROUTING -o "$lan" -j MARK --set-mark 0x3

# tu regu³y które wy³api± ruch p2p
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --sport 6881:6889 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o eth1 -p udp --sport 6881:6889 -j MARK --set-mark 0x4
# iptables -t mangle -A POSTROUTING -o eth1  -m ipp2p ... -j MARK --set-mark 0x4
# iptables -t mangle -A POSTROUTING -o "$lan"   -m ipp2p ... -j MARK --set-mark 0x4

# ssh
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --sport 22 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --dport 22 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --dport 23 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --sport 23 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --sport 21 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --dport 21 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --sport 5801 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --dport 5801 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --sport 5900 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --dport 5900 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --sport 5901 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o eth1 -p tcp --dport 5901 -j MARK --set-mark 0x2

#
# Przychodzacy
#

# q3
iptables -t mangle -A POSTROUTING -o br0 -p udp --dport 27963 -j MARK --set-mark 0x1
iptables -t mangle -A POSTROUTING -o br0 -p udp --dport 27963 -j RETURN
iptables -t mangle -A POSTROUTING -o br0 -p udp --dport 44830 -j MARK --set-mark 0x1
iptables -t mangle -A POSTROUTING -o br0 -p udp --dport 44830 -j RETURN
iptables -t mangle -A POSTROUTING -o br0 -p udp --sport 27963 -j MARK --set-mark 0x1
iptables -t mangle -A POSTROUTING -o br0 -p udp --sport 27963 -j RETURN
iptables -t mangle -A POSTROUTING -o br0 -p udp --sport 44830 -j MARK --set-mark 0x1
iptables -t mangle -A POSTROUTING -o br0 -p udp --sport 44830 -j RETURN

#default
iptables -t mangle -A POSTROUTING -o br0 -j MARK --set-mark 0x3
# iptables -t mangle -A POSTROUTING -o "$lan" -j MARK --set-mark 0x3

# tu regu³y które wy³api± ruch p2p
iptables -t mangle -A POSTROUTING -o br0 -p tcp --sport 6881:6889 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p udp --sport 6881:6889 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p tcp --dport 6881:6889 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p udp --dport 6881:6889 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p tcp --sport 412 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p udp --sport 412 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p tcp --dport 412 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p udp --dport 412 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p tcp --sport 4662 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p udp --sport 4662 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p tcp --dport 4662 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p udp --dport 4662 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p tcp --sport 4672 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p udp --sport 4672 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p tcp --dport 4672 -j MARK --set-mark 0x4
iptables -t mangle -A POSTROUTING -o br0 -p udp --dport 4672 -j MARK --set-mark 0x4
# iptables -t mangle -A POSTROUTING -o br0  -m ipp2p ... -j MARK --set-mark 0x4
# iptables -t mangle -A POSTROUTING -o "$lan"   -m ipp2p ... -j MARK --set-mark 0x4

# ssh
iptables -t mangle -A POSTROUTING -o br0 -p tcp --sport 22 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o br0 -p tcp --dport 22 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o br0 -p tcp --dport 23 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o br0 -p tcp --sport 23 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o br0 -p tcp --sport 21 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o br0 -p tcp --dport 21 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o br0 -p tcp --sport 5801 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o br0 -p tcp --dport 5801 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o br0 -p tcp --sport 5900 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o br0 -p tcp --dport 5900 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o br0 -p tcp --sport 5901 -j MARK --set-mark 0x2
iptables -t mangle -A POSTROUTING -o br0 -p tcp --dport 5901 -j MARK --set-mark 0x2

