/*
 * HTBClassJPanel.java
 *
 * Created on 19 styczeń 2008, 16:57
 */
package htb.gui;

import htb.*;
import javax.swing.JOptionPane;

/**
 *
 * @author  rob
 */
public class HTBClassJPanel extends javax.swing.JPanel {

    private HTBClass c;
    private HTBJApplet applet;

    /** Creates new form HTBClassJPanel */
    public HTBClassJPanel() {
        this(null, null);
    }

    public HTBClassJPanel(HTBClass c, HTBJApplet applet) {
        this.c = c;
        this.applet = applet;
        initComponents();
        if (c != null) {
            nameJTextField.setText(c.getName());
            rateJTextField.setText(c.getRate().toString());
            ceilJTextField.setText(c.getCeil().toString());
            prioJTextField.setText(((Integer) c.getPrio()).toString());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        rateJTextField = new javax.swing.JTextField();
        ceilJTextField = new javax.swing.JTextField();
        prioJTextField = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rateJSlider = new javax.swing.JSlider();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(3, 5, 2, 5)));
        setMaximumSize(new java.awt.Dimension(484, 47));
        setMinimumSize(new java.awt.Dimension(484, 47));
        setPreferredSize(new java.awt.Dimension(484, 47));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel1.setLabelFor(nameJTextField);
        jLabel1.setText("name:");
        add(jLabel1);
        jLabel1.setBounds(4, 7, 37, 15);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setLabelFor(rateJSlider);
        jLabel2.setText("rate:");
        add(jLabel2);
        jLabel2.setBounds(205, 30, 35, 15);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel3.setLabelFor(ceilJTextField);
        jLabel3.setText("ceil:");
        add(jLabel3);
        jLabel3.setBounds(315, 7, 24, 15);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel4.setLabelFor(prioJTextField);
        jLabel4.setText("prio:");
        add(jLabel4);
        jLabel4.setBounds(416, 7, 27, 15);

        nameJTextField.setToolTipText("Class name");
        nameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameJTextFieldFocusLost(evt);
            }
        });
        add(nameJTextField);
        nameJTextField.setBounds(41, 6, 162, 18);

        rateJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rateJTextFieldFocusLost(evt);
            }
        });
        add(rateJTextField);
        rateJTextField.setBounds(240, 6, 65, 18);

        ceilJTextField.setToolTipText("Upper bandwidth limit for class");
        ceilJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ceilJTextFieldFocusLost(evt);
            }
        });
        add(ceilJTextField);
        ceilJTextField.setBounds(339, 6, 65, 18);

        prioJTextField.setToolTipText("Class priority (the lower number the higher priority)");
        prioJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prioJTextFieldFocusLost(evt);
            }
        });
        add(prioJTextField);
        prioJTextField.setBounds(444, 6, 34, 18);

        removeButton.setFont(new java.awt.Font("Verdana", 0, 11));
        removeButton.setText("Remove");
        removeButton.setToolTipText("Delete this class");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        add(removeButton);
        removeButton.setBounds(41, 26, 81, 18);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setLabelFor(rateJTextField);
        jLabel5.setText("rate:");
        add(jLabel5);
        jLabel5.setBounds(205, 7, 35, 15);

        rateJSlider.setMajorTickSpacing(30);
        rateJSlider.setMinorTickSpacing(5);
        rateJSlider.setToolTipText("Percentage usage of total bandwidth");
        rateJSlider.setValue(0);
        rateJSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rateJSliderMouseDragged(evt);
            }
        });
        rateJSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rateJSliderMouseDragged(evt);
            }
        });
        add(rateJSlider);
        rateJSlider.setBounds(235, 30, 248, 16);
    }// </editor-fold>//GEN-END:initComponents
    private void nameJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJTextFieldFocusLost
        c.setName(nameJTextField.getText());
    }//GEN-LAST:event_nameJTextFieldFocusLost

    private void rateJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rateJTextFieldFocusLost
        c.setRate(new Bandwidth(rateJTextField.getText()));
        applet.updateSliders();
    }//GEN-LAST:event_rateJTextFieldFocusLost

    private void ceilJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ceilJTextFieldFocusLost
        c.setCeil(new Bandwidth(ceilJTextField.getText()));
    }//GEN-LAST:event_ceilJTextFieldFocusLost

    private void prioJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prioJTextFieldFocusLost
        try {
            c.setPrio(Integer.parseInt(prioJTextField.getText()));
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null,
                    "Wrong format of bandwidth!", "Error", JOptionPane.ERROR_MESSAGE);
            prioJTextField.setText("1");
            c.setPrio(1);
        }

    }//GEN-LAST:event_prioJTextFieldFocusLost

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        applet.getGenerator().getOutclasses().remove(c);
        applet.getGenerator().getInclasses().remove(c);
        applet.updateClassesPanels();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void rateJSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rateJSliderMouseDragged
        float val = 1.0f * rateJSlider.getValue() / 100;
        c.setPercent(val);
        applet.updateRates();
    }//GEN-LAST:event_rateJSliderMouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ceilJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField prioJTextField;
    javax.swing.JSlider rateJSlider;
    javax.swing.JTextField rateJTextField;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
    public HTBClass getCl() {
        return c;
    }

    public void setCl(HTBClass c) {
        this.c = c;
    }
}
